{% set name = "CellProfiler" %}
{% set version = "4.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/{{ name  }}/archive/v{{ version }}.tar.gz
  sha256: "8ceb80c95eb777bdb995411279a2f9ce971c685fca085c59db8830f9d51b95d1"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"
  #skip: True  # this is using for some reason up to 3GB of memory and crashes CCI, build and push locally
  #skip: True  # [win or osx or py3k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python  >=3.8
    - pip
    - cython
    - openjdk
    - pytest
  run:
    - python  >=3.8
    - boto3
    - centrosome 
    - docutils
    - h5py  >=2.10
    - inflect
    - imageio
    - javabridge
    - joblib
    - mahotas
    - openjdk
    - matplotlib-base ==3.1.3
    - mysqlclient ==1.4.6
    - numpy  >=1.18.2
    - prokaryote
    - python-bioformats
    - pyzmq
    - raven
    - requests
    - scikit-image  >=0.17.2
    - scikit-learn  >=0.20
    - scipy         >=1.4.1
    - six
    - wxpython
    - future

test:
  imports:
    - cellprofiler

about:
  home: https://github.com/CellProfiler/CellProfiler
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: "CellProfiler is free, open-source software for quantitative analysis of biological images"
  description: |
     CellProfiler is free, open-source software for quantitative analysis of biological images.No prior experience in programming or computer vision is required.

extra:
  container:
    extended-base: true
  recipe-maintainers:
    - sunyi000
