{% set name = "ncbimeta" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ktmeaton/NCBImeta/archive/v{{ version }}.tar.gz
  sha256: b767385dffb1e146266a5b8e8d4cf0daf3044dcb32adb69b1c1c2013ff509ccc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >3
  run:
    - python >3
    - biopython >=1.74,<1.77
    - pyyaml >=5.1.2
    - lxml >=4.4.2
    - numpy >=1.16.4

test:
  commands:
    - NCBImeta.py --version
    - NCBImetaExport.py --version
    - NCBImetaJoin.py --version
    - NCBImetaAnnotateReplace.py --version
    - NCBImetaAnnotateConcatenate.py --version

about:
  home: https://github.com/ktmeaton/NCBImeta
  license: MIT
  license_file: LICENSE
  summary: Efficient and comprehensive metadata acquisition from the NCBI databases (includes SRA).
