{% set package = "ucsc-fatovcf" %}
{% set program = "faToVcf" %}
{% set version = "389" %}
{% set sha256 = "717264ffc6e0fdb2c4d5646eefe9381f02421590655c0ebe846af63cebf5a7d8" %}

package:
  name: "{{ package }}"
  version: "{{ version }}"

source:
  url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v{{ version }}.src.tgz"
  sha256: "{{ sha256 }}"

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl
    - zlib

  run:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl
    - zlib

test:
  commands:
    # just check for existence, because the individual packages have no unified behavior
    - which {{ program }}

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  summary: "Extract VCF from a multi-sequence FASTA alignment"
