{% set name = "pyrodigal" %}
{% set version = "0.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/a1/de/142a6ae3b49fabc663fa36c852e6401d43eb36bf3f2e24bbccf94aad410f/pyrodigal-0.4.3.tar.gz
  sha256: 5a3d16f50c42444484aa9eeb5f879b95509b65e973d562be75dfa8d54deac034

build:
  number: 0
  skip: True  #[py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/althonos/pyrodigal
  license: GPL-3
  license_family: GPL
  license_file: COPYING
  summary: Python bindings to Prodigal, an ORF finder for microbial sequences.

extra:
  recipe-maintainers:
    - althonos
