{% set name = "seq2science" %}
{% set version = "v0.4.3_argcomplete_test" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vanheeringen-lab/seq2science/archive/v{{ version }}.tar.gz
  sha256: a0b1437ba22448fe42e872ab51e22cc3900df67fbb2f936f31d30e3eb75dd55f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - toml
    - setuptools
  run:
    - python=3.8
    - snakemake=5.32.0
    - conda=4.9.2
    - mamba=0.7.10
    - genomepy=0.9.1
    - biopython=1.74
    - filelock=3.0.12
    - pyyaml=5.3.1
    - pandas_schema=0.3.5
    - trackhub=0.1.2019.12.24
    - pysradb=0.11.1
    - matplotlib-base=3.3.2
    - xdg=5.0.1
    - argcomplete=1.12.2

test:
  commands:
    - which seq2science
    - seq2science --help
    - seq2science init atac-seq
    - mkdir --parents results/fastq; touch results/fastq/GSM28374{88,89,90,91,92,93}.fastq.gz  # no lookup online for layout
    - mkdir --parents genomes/Bl71nemr; touch genomes/Bl71nemr/Bl71nemr{.fa,.fa.sizes,.gaps.bed,.annotation.gtf,.annotation.bed}
    - echo -e "chr1\t100000" > genomes/Bl71nemr/Bl71nemr.fa.sizes
    - seq2science run atac-seq --dryrun --snakemakeOption resources={mem_gb:100}
    - chmod -R 777 .   # make sure everything can be deleted
    - complete -p | grep seq2science  # test for tab-completion

about:
  home: https://vanheeringen-lab.github.io/seq2science
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: "Automated preprocessing of Next-Generation-Sequencing data."
  dev_url: https://github.com/vanheeringen-lab/seq2science
  doc_url: https://vanheeringen-lab.github.io/seq2science

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
    - siebrenf
    - tilschaef
