{% set version = "1.10" %}
{% set sha256 = "deac5506ee3aa30a2041ca11000068d5b0a6c21cf25b76841b6c95d6dd4d5fc2" %}

package:
  name: hmftools-gripss
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/gripss-v{{ version }}/gripss-{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - 'gripss 2>&1 | grep usage'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/gripss
  license: GPL-3.0-only
  license_family: GPL
  summary: 'GRIPSS applies a set of filtering and post processing steps on GRIDSS paired tumor-normal output to produce a high confidence set of somatic SV for a tumor sample.'
