{% set version = '0.6.20' %}
{% set github = "https://github.com/hbc/bcbioBase" %}

package:
  name: r-bcbiobase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 034bec623dac26e634007a6c2c3ce1648c09979954c511c4b1c589b723a09ee2

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
      # Depends:
    - r-base
      # Imports:
    - bioconductor-s4vectors
    - r-basejump >=0.13.3
    - r-cli >=2.2
    - r-goalie >=0.4.11
    - r-plyr >=1.8
    - r-stringr >=1.4
      # Suggests:
    - r-rdrop2
  run:
      # Depends:
    - r-base
      # Imports:
    - bioconductor-s4vectors
    - r-basejump >=0.13.3
    - r-cli >=2.2
    - r-goalie >=0.4.11
    - r-plyr >=1.8
    - r-stringr >=1.4
      # Suggests:
    - r-rdrop2

test:
  commands:
    - $R -e "library('bcbioBase')"

about:
  home: http://bioinformatics.sph.harvard.edu/bcbioBase/
  dev_url: "{{ github }}"
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Base functions and generics for bcbio R packages.

extra:
  recipe-maintainers:
    - mjsteinbaugh
