{% set name = "scaden" %}
{% set version = "1.0.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a9ee633cf7af932c10633f5b66a0554dbd94c73c5d0cea8614ac6bc07f09447

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - python >=3
    - pip
    - twine
  run:
    - python >=3
    - pandas
    - numpy >=1.16.0,<1.19.0
    - numpy
    - scikit-learn
    - scipy  1.4.1
    - seaborn
    - tensorflow >=2
    - matplotlib-base
    - scanpy
    - tqdm
    - click

test:
  commands:
    - scaden --help

about:
  home: https://github.com/KevinMenden/scaden
  license: MIT
  summary: Cell type deconvolution using single cell data
