{% set name = "perl-text-csv_xs" %}
{% set version = "1.45" %}
{% set sha256 = "128a66c946a0d9d439cbb74212b3dced8dcdb5bd0e1b78d98cfb87059f4a416f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.45.tgz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-harness
    - perl-text-csv

  run:
    - perl
    - perl-test-harness
    - perl-text-csv

test:
  imports:
    - Text::CSV_XS

about:
  home: https://metacpan.org/pod/Text::CSV_XS
  license: perl_5
  summary: 'Text::CSV_XS - comma-separated values manipulation routines'
